### ISSUE TITLE
mc-benchmark seems broken

### ISSUE THREAD

**Issue by matteo335** [Krutoy242/mc-benchmark#4]
I remember using the tool one year ago, but now it's not working anymore

PS C:\Users\matte\curseforge\minecraft\Instances\ChaosCraft> npx mc-benchmark
🔹 Opening debug.log  ✔
🔹 Looking for JEI plugins  ✔
🔹 Mods loading timefile:///C:/Users/matte/AppData/Local/npm-cache/_npx/d746e29339dd2ad6/node_modules/mc-benchmark/index.js:332
    return groups.time == 's'
                  ^

TypeError: Cannot read properties of undefined (reading 'time')
    at toSeconds (file:///C:/Users/matte/AppData/Local/npm-cache/_npx/d746e29339dd2ad6/node_modules/mc-benchmark/index.js:332:19)
    at parseDebugLog (file:///C:/Users/matte/AppData/Local/npm-cache/_npx/d746e29339dd2ad6/node_modules/mc-benchmark/index.js:338:71)

Node.js v22.15.0

**Comment by Krutoy242** [comment]
What MC version?

**Comment by Krutoy242** [comment]
I completely refactored and rewritten the tool.
Try it again. Use `npx mc-benchmark@latest` to automatically run latest version.

**Comment by matteo335** [comment]
I don't know if it's only on my end but I cannot use mc-benchmark anymore. After opening this issue I was able to use the tool when I downgraded the index file using the 1.0.8 version, but now even after testing on both CMD administrator and no administrator and deleting the npx cache/folder & reinstalling NodeJS I cannot use the tool

"'mc-benchmark' is not recognized as an internal
or external command, an executable program or a command file."
![Image](https://github.com/user-attachments/assets/70e2dec4-ee6e-46b7-aeef-77524c21d641)

**Comment by Krutoy242** [comment]
This is not a problem with `mc-benchmark` itself - my script could not be found on your machine at all. This is related to Node and how it looking for executables.

Try this commands, one by one. It will install `mc-benchmark` locally in the same folder as your modpack:
```cs
npm init -y
npm i -D mc-benchmark@latest
npx mc-benchmark
```

**Comment by matteo335** [comment]
I just tested another version of NodeJS and the instructions you gave me, but infortunately it's still not working.
There is the command list:

[CMD-commands.txt](https://github.com/user-attachments/files/20139779/CMD-commands.txt)

**Comment by Krutoy242** [comment]
Oh, I found a problem, thank you for providing more info! Seems like i just pointed to a wrong file for launch script.
You can use the tool now by directly calling the source file instead of shortcut. I will release fix in next days.

This command should work:
```less
node node_modules/mc-benchmark/dist/mc-benchmark.js
```

**Comment by Krutoy242** [comment]
Finally, i fixed and made it work as it should by `npx mc-benchmark@latest`. Please report if its work fine now.

![Image](https://github.com/user-attachments/assets/6d25c25a-dc09-4956-a8f3-0a71107ecbd3)

**Comment by matteo335** [comment]
I was able to use `npx mc-benchmark@latest`. However simple `npx mc-benchmark` is still not recognized

The command did not create a file by itself but printed everything in the console instead, after creating a .md file I could confirm the result is working properly

**Comment by Krutoy242** [comment]
> I was able to use `npx mc-benchmark@latest`. However simple `npx mc-benchmark` is still not recognized
> 
> The command did not create a file by itself but printed everything in the console instead, after creating a .md file I could confirm the result is working properly

Oh, yes, sorry. I changed usage of the program and forgot to mention that in the readme.

Now, you need to pipe output of the console into the file with `>` operator. You can do it in any console like this:
```sh
npx mc-benchmark@latest > benchmark.md
```

**Comment by Krutoy242** [comment]
Ok, i fixed and updated the readme. Seems like everything is ok now! Thanks for helping me debug the program.
